apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui-ing
spec:
  ingressClassName: public
  rules:
  - host: comfyui.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: comfyui-svc
            port:
              number: 8188