apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui-ing
spec:
  ingressClassName: public
  rules:
  - host: openwebui.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui-svc
            port:
              number: 8080
  - host: openwebui.omen.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui-svc
            port:
              number: 8080              